import json
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import config

def parse_notes(notes_text):
    heading  = ""
    bullets  = []
    summary  = ""
    question = ""
    current  = ""

    for line in notes_text.split("\n"):
        line = line.strip()
        if line.startswith("HEADING:"):
            heading = line.replace("HEADING:", "").strip()
        elif line.startswith("BULLETS:"):
            current = "bullets"
        elif line.startswith("SUMMARY:"):
            summary = line.replace("SUMMARY:", "").strip()
            current = ""
        elif line.startswith("QUESTION:"):
            question = line.replace("QUESTION:", "").strip()
            current = ""
        elif current == "bullets" and line.startswith("-"):
            bullets.append(line[1:].strip())

    return heading, bullets, summary, question

def build_pdf(notes):
    output_path = os.path.join(config.OUTPUT_DIR, "study_notes.pdf")
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#2C3E50"),
        spaceAfter=6
    )
    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#2980B9"),
        spaceBefore=12,
        spaceAfter=4
    )
    bullet_style = ParagraphStyle(
        "BulletStyle",
        parent=styles["Normal"],
        fontSize=10,
        leftIndent=15,
        spaceAfter=3,
        textColor=colors.HexColor("#2C3E50")
    )
    summary_style = ParagraphStyle(
        "SummaryStyle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#555555"),
        backColor=colors.HexColor("#EBF5FB"),
        borderPadding=(6, 6, 6, 6),
        spaceAfter=4
    )
    question_style = ParagraphStyle(
        "QuestionStyle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#1A5276"),
        borderPadding=(6, 6, 6, 6),
        spaceAfter=6
    )
    time_style = ParagraphStyle(
        "TimeStyle",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#999999"),
        spaceAfter=2
    )

    story = []

    # Title page header
    story.append(Paragraph("Smart Study Notes", title_style))
    story.append(Paragraph("Auto-generated by Lecture Notes AI", styles["Normal"]))
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#2980B9")))
    story.append(Spacer(1, 0.5*cm))

    for note in notes:
        heading, bullets, summary, question = parse_notes(note["notes"])

        if not heading:
            continue

        # Timestamp
        start = note.get("start_time", 0)
        end   = note.get("end_time", 0)
        story.append(Paragraph(f"Time: {start}s — {end}s", time_style))

        # Section heading
        story.append(Paragraph(f"{heading}", heading_style))

        # Slide image
        frame_file = note.get("frame_file", "")
        if frame_file:
            img_path = os.path.join(config.FRAMES_DIR, frame_file)
            if os.path.exists(img_path):
                try:
                    img = Image(img_path, width=8*cm, height=4.5*cm)
                    story.append(img)
                    story.append(Spacer(1, 0.2*cm))
                except:
                    pass

        # Bullet points
        for b in bullets:
            story.append(Paragraph(f"• {b}", bullet_style))

        # Summary
        if summary:
            story.append(Spacer(1, 0.2*cm))
            story.append(Paragraph(f"Summary: {summary}", summary_style))

        # Practice question
        if question:
            story.append(Paragraph(f"Practice Q: {question}", question_style))

        story.append(HRFlowable(width="100%", thickness=0.5,
                                color=colors.HexColor("#CCCCCC")))
        story.append(Spacer(1, 0.3*cm))

    doc.build(story)
    print(f"PDF created successfully!")
    print(f"Saved to: {output_path}")
    return output_path

if __name__ == "__main__":
    notes_path = os.path.join(config.PROCESSED_DIR, "notes.json")

    with open(notes_path, "r", encoding="utf-8") as f:
        notes = json.load(f)

    print(f"Building PDF from {len(notes)} notes...")
    path = build_pdf(notes)
    print(f"\nOpen your PDF here:\n{path}")